// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIU9508jDFool2Fcuv1rqITuvZu0uy2eE',
    appId: '1:960420253241:web:6dc9abd4e52480b69e07e8',
    messagingSenderId: '960420253241',
    projectId: 'bookstore-5ada5',
    authDomain: 'bookstore-5ada5.firebaseapp.com',
    storageBucket: 'bookstore-5ada5.appspot.com',
    measurementId: 'G-39VW1WVVSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw6b7tu9uDG4hT7zgAEBnA3nsK8FSCHMc',
    appId: '1:960420253241:android:c778913d7ff64edc9e07e8',
    messagingSenderId: '960420253241',
    projectId: 'bookstore-5ada5',
    storageBucket: 'bookstore-5ada5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf_3W-zlHElMqryKKKoXbn0lYqFSblOeQ',
    appId: '1:960420253241:ios:01f0e8d225cbd1599e07e8',
    messagingSenderId: '960420253241',
    projectId: 'bookstore-5ada5',
    storageBucket: 'bookstore-5ada5.appspot.com',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf_3W-zlHElMqryKKKoXbn0lYqFSblOeQ',
    appId: '1:960420253241:ios:01f0e8d225cbd1599e07e8',
    messagingSenderId: '960420253241',
    projectId: 'bookstore-5ada5',
    storageBucket: 'bookstore-5ada5.appspot.com',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIU9508jDFool2Fcuv1rqITuvZu0uy2eE',
    appId: '1:960420253241:web:89bc6ecfa3a5d9c09e07e8',
    messagingSenderId: '960420253241',
    projectId: 'bookstore-5ada5',
    authDomain: 'bookstore-5ada5.firebaseapp.com',
    storageBucket: 'bookstore-5ada5.appspot.com',
    measurementId: 'G-BGY9ZXGMPP',
  );
}
